import * as Phaser from 'phaser';

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: 'BootScene' });
  }

  preload() {
    // Load pre-generated PNG tile assets (generated by scripts/generate-tiles.js)
    this.load.image('tile_grass',            '/assets/tilesets/grass.png');
    this.load.image('tile_dirt',             '/assets/tilesets/dirt.png');
    this.load.image('tile_tree',             '/assets/tilesets/tree.png');
    this.load.image('tile_building_wall',    '/assets/tilesets/building_wall.png');
    this.load.image('tile_roof_dark',        '/assets/tilesets/roof_dark.png');
    this.load.image('tile_roof_red',         '/assets/tilesets/roof_red.png');
    this.load.image('tile_building_window',  '/assets/tilesets/building_window.png');
    this.load.image('tile_fence_h',          '/assets/tilesets/fence_h.png');
    this.load.image('tile_fence_v',          '/assets/tilesets/fence_v.png');
    this.load.image('tile_water',            '/assets/tilesets/water.png');
    this.load.image('tile_sign',             '/assets/tilesets/sign.png');
    this.load.image('tile_floor',            '/assets/tilesets/floor.png');
    this.load.image('tile_flower',           '/assets/tilesets/flower.png');
    this.load.image('tile_door',             '/assets/tilesets/door.png');
    this.load.image('tile_stone',            '/assets/tilesets/stone.png');
  }

  create() {
    this.generatePlayerTextures();
    this.generateNPCTextures();
    this.generateUITextures();
    this.scene.start('WorldScene');
  }

  // Helper: create a canvas texture using the Canvas 2D API
  private tex(key: string, w: number, h: number, fn: (ctx: CanvasRenderingContext2D) => void) {
    const t = this.textures.createCanvas(key, w, h);
    if (!t) return;
    const ctx = t.getContext();
    fn(ctx);
    t.refresh();
  }

  // Draw a chibi character sprite onto a 32x32 canvas context
  private drawChibi(ctx: CanvasRenderingContext2D, opts: {
    skinColor: string;
    hairColor: string;
    outfitColor: string;
    hairStyle: 'normal' | 'long' | 'bald' | 'short';
    tieColor?: string;
    back?: boolean;
  }) {
    const { skinColor, hairColor, outfitColor, hairStyle, tieColor, back = false } = opts;
    const cx = 16;

    // Shoes
    ctx.fillStyle = '#101010';
    ctx.fillRect(cx - 6, 28, 5, 3);
    ctx.fillRect(cx + 1, 28, 5, 3);

    // Legs
    ctx.fillStyle = '#202040';
    ctx.fillRect(cx - 5, 22, 4, 7);
    ctx.fillRect(cx + 1, 22, 4, 7);

    // Body
    ctx.fillStyle = outfitColor;
    ctx.fillRect(cx - 6, 13, 12, 10);

    // Arms
    ctx.fillStyle = outfitColor;
    ctx.fillRect(cx - 10, 14, 4, 8);
    ctx.fillRect(cx + 6, 14, 4, 8);

    // Hands (skin)
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx - 10, 21, 4, 3);
    ctx.fillRect(cx + 6, 21, 4, 3);

    // Neck
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx - 2, 10, 4, 4);

    // Head
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx - 5, 3, 10, 9);

    // Hair
    if (hairStyle !== 'bald') {
      ctx.fillStyle = hairColor;
      if (hairStyle === 'long') {
        // Long hair - covers top + side extensions
        ctx.fillRect(cx - 5, 1, 10, 5);
        ctx.fillRect(cx - 7, 3, 2, 10);
        ctx.fillRect(cx + 5, 3, 2, 10);
      } else if (hairStyle === 'short') {
        ctx.fillRect(cx - 5, 1, 10, 4);
      } else {
        // Normal hair
        ctx.fillRect(cx - 5, 1, 10, 5);
        ctx.fillRect(cx - 6, 3, 2, 5);
        ctx.fillRect(cx + 4, 3, 2, 5);
      }
    }

    // Eyes (front only)
    if (!back) {
      ctx.fillStyle = '#202020';
      ctx.fillRect(cx - 3, 8, 2, 2);
      ctx.fillRect(cx + 1, 8, 2, 2);
      // Mouth hint
      ctx.fillStyle = '#C08060';
      ctx.fillRect(cx - 1, 10, 2, 1);
    }

    // Tie detail
    if (tieColor) {
      ctx.fillStyle = tieColor;
      ctx.fillRect(cx - 1, 14, 2, 7);
    }

    // Subtle body outline
    ctx.strokeStyle = 'rgba(0,0,0,0.15)';
    ctx.lineWidth = 0.5;
    ctx.strokeRect(cx - 6, 13, 12, 10);
    ctx.strokeRect(cx - 5, 3, 10, 9);
  }

  private generatePlayerTextures() {
    // player_front: used for down direction
    this.tex('player_front', 32, 32, (ctx) => {
      this.drawChibi(ctx, {
        skinColor: '#F0C090',
        hairColor: '#6B3E2A',
        outfitColor: '#2850A0',
        hairStyle: 'normal',
        back: false,
      });
    });

    // player_back: used for up direction
    this.tex('player_back', 32, 32, (ctx) => {
      this.drawChibi(ctx, {
        skinColor: '#F0C090',
        hairColor: '#6B3E2A',
        outfitColor: '#2850A0',
        hairStyle: 'normal',
        back: true,
      });
    });

    // player_right: side-profile view — used for right (and flipped for left)
    this.tex('player_right', 32, 32, (ctx) => {
      this.drawChibiSide(ctx, {
        skinColor: '#F0C090',
        hairColor: '#6B3E2A',
        outfitColor: '#2850A0',
      });
    });
  }

  // Draw a chibi character in side profile (facing right)
  private drawChibiSide(ctx: CanvasRenderingContext2D, opts: {
    skinColor: string;
    hairColor: string;
    outfitColor: string;
  }) {
    const { skinColor, hairColor, outfitColor } = opts;
    const cx = 16;

    // Shoes (side view — one visible, one slightly behind)
    ctx.fillStyle = '#101010';
    ctx.fillRect(cx + 1, 28, 7, 3);   // front shoe
    ctx.fillRect(cx - 2, 28, 5, 2);   // back shoe (partial)

    // Legs (side — slight offset for walk pose)
    ctx.fillStyle = '#202040';
    ctx.fillRect(cx + 2, 22, 4, 7);   // front leg
    ctx.fillRect(cx - 1, 23, 4, 6);   // back leg

    // Body (narrower from side)
    ctx.fillStyle = outfitColor;
    ctx.fillRect(cx - 3, 13, 9, 10);

    // Near arm (visible from side)
    ctx.fillStyle = outfitColor;
    ctx.fillRect(cx + 5, 14, 3, 8);

    // Hand (skin)
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx + 5, 21, 3, 3);

    // Neck
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx - 1, 10, 3, 4);

    // Head (side profile — slightly offset forward)
    ctx.fillStyle = skinColor;
    ctx.fillRect(cx, 3, 9, 9);

    // Nose hint
    ctx.fillStyle = '#D09070';
    ctx.fillRect(cx + 8, 7, 2, 2);

    // Eye (single eye from side)
    ctx.fillStyle = '#202020';
    ctx.fillRect(cx + 6, 6, 2, 2);

    // Hair (side profile)
    ctx.fillStyle = hairColor;
    ctx.fillRect(cx, 1, 9, 5);         // top
    ctx.fillRect(cx - 1, 3, 2, 7);    // back of head
    ctx.fillRect(cx + 8, 2, 3, 4);    // front tuft

    // Subtle outline
    ctx.strokeStyle = 'rgba(0,0,0,0.15)';
    ctx.lineWidth = 0.5;
    ctx.strokeRect(cx - 3, 13, 9, 10);
    ctx.strokeRect(cx, 3, 9, 9);
  }

  private generateNPCTextures() {
    // Each NPC with distinctive appearance matching the real person
    const npcs: Array<{
      hairStyle: 'normal' | 'long' | 'bald' | 'short';
      hairColor: string;
      outfitColor: string;
      tieColor?: string;
    }> = [
      // 0: Marc Andreessen — bald, navy blue suit
      { hairStyle: 'bald',   hairColor: '#202020', outfitColor: '#1A237E' },
      // 1: Ben Horowitz — short dark hair, dark suit, red tie
      { hairStyle: 'short',  hairColor: '#2C2C2C', outfitColor: '#2C2C3E', tieColor: '#880000' },
      // 2: Lisa Su — normal black hair, red/orange blazer
      { hairStyle: 'normal', hairColor: '#1A1A1A', outfitColor: '#CC4400' },
      // 3: Alexandr Wang — normal dark hair, gray casual
      { hairStyle: 'normal', hairColor: '#2C2C2C', outfitColor: '#607080' },
      // 4: Jensen Huang — silver hair, black leather jacket
      { hairStyle: 'normal', hairColor: '#C0C0C0', outfitColor: '#1A1A1A' },
      // 5: Sarah Guo — long dark hair, pink top
      { hairStyle: 'long',   hairColor: '#1A1A1A', outfitColor: '#E07090' },
      // 6: Elad Gil — normal dark hair, purple shirt
      { hairStyle: 'normal', hairColor: '#2C2C2C', outfitColor: '#604090' },
      // 7: Andrew Chen — normal dark hair, orange hoodie
      { hairStyle: 'normal', hairColor: '#2C2C2C', outfitColor: '#CC6600' },
      // 8: Sonal Chokshi — normal dark hair, teal outfit
      { hairStyle: 'normal', hairColor: '#1A1A1A', outfitColor: '#207070' },
      // 9: David George — short dark hair, dark suit, red tie
      { hairStyle: 'short',  hairColor: '#2C2C2C', outfitColor: '#2C2C3E', tieColor: '#880000' },
    ];

    npcs.forEach((npc, i) => {
      this.tex(`npc_${i}`, 32, 32, (ctx) => {
        this.drawChibi(ctx, {
          skinColor: '#F0C090',
          hairColor: npc.hairColor,
          outfitColor: npc.outfitColor,
          hairStyle: npc.hairStyle,
          tieColor: npc.tieColor,
          back: false,
        });
      });
    });
  }

  private generateUITextures() {
    const g = this.make.graphics({ x: 0, y: 0 });

    // HP bar background
    g.fillStyle(0x404040); g.fillRect(0, 0, 200, 20);
    g.fillStyle(0x202020); g.fillRect(2, 2, 196, 16);
    g.generateTexture('hpbar_bg', 200, 20);

    // HP bar fill
    g.clear();
    g.fillStyle(0x40C840); g.fillRect(0, 0, 196, 16);
    g.generateTexture('hpbar_fill', 196, 16);

    // Pokéball
    g.clear();
    g.fillStyle(0xFF0000); g.fillCircle(12, 8, 12);
    g.fillStyle(0xFFFFFF); g.fillCircle(12, 16, 12);
    g.fillStyle(0x000000); g.fillRect(0, 11, 24, 2);
    g.fillCircle(12, 12, 4);
    g.fillStyle(0xFFFFFF); g.fillCircle(12, 12, 2);
    g.generateTexture('pokeball', 24, 24);

    g.destroy();
  }
}
